services:
  postgres:
    image: postgres:latest
    container_name: myZythologue_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myAPIREST_zythlogie_ab
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
     - .:/usr/src/APIRESTBeerProject
     - /usr/src/APIRESTBeerProject/node_modules
    depends_on:
      - postgres

volumes:
  postgres_data: